feat: getUploadWidgetOptions, generateSignatureCallback, generateUploadWidgetResultCallback (#165)
# Description

This creates a new set of helpers that will help framework libraries
reduce the boilerplate needed to instantiate new instances of the upload
widget.

* getUploadWidgetOptions: this takes in a set of options that deal with
the configuration of the upload widget, including account credentials
and signature callback function
* generateSignatureCallback: this generates a new callback function that
given an endpoint and fetcher (like the fetch API), will make it easier
to pass the resulting function to the widget options above
* generateUploadWidgetResultCallback: when uploading with the widget,
different events are produced depending on the state of the upload, this
helps manage all of the different events via a single callback function
with the ability to pass in and tap into the different events

## Issue Ticket Number

Fixes #164 

## Usage

```
const signatureCallback = generateSignatureCallback({
  signatureEndpoint: '/asdf',
  fetch
})

const uploadOptions = getUploadWidgetOptions({
  signatureCallback
}, {
  cloud: {
    cloudName: 'testcloud',
    apiKey: 'abcd1234'
  }
});

const resultsCallback = generateUploadWidgetResultCallback({
  onError: (uploadError) => {
    // Example on storing error
    // setError(uploadError);
  },
  onResult: (uploadResult) => {
    // Example of storing results on any event
    // setResults(uploadResult);
  },
  onSuccess: (uploadResult) => {
    // Tapping into individual events
  }
});

cloudinary.createUploadWidget(uploadOptions, resultsCallback);
```